### ISSUE TITLE
Implement the synthesis metadata spec

### ISSUE THREAD

**Issue by theacodes** [googleapis/synthtool#126]
[Internal spec](https://docs.google.com/document/d/1GQXENoNKQJDpCI2MOZIcTm6DeJXQvU0xqOMnCoU3jVc/edit#heading=h.ff16o99kfquv).

- [x] Create protos (or JSON-RPC or something) for the Metadata format. (#127)
- [x] Create a means for sources to amend the metadata during generation. (#132 for git sources, #136 for artman, #149 for templates)
- [x] Create a means for generators to amend the metadata during generation (#155).
- [x] Figure out how to deal with FileSets and such (spec updated).
- [x] Output the metadata to `synth.metadata`.

**Comment by theacodes** [comment]
Cool, reporting is all done, just have to updated autosynth to use the module-style invocation so the metadata file gets written. :)

**Comment by theacodes** [comment]
This is done now. :)
